# Generated by Django 2.1.7 on 2019-04-23 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_auto_20190423_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresss',
            name='stu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
    ]
