# Generated by Django 2.1.7 on 2019-04-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_auto_20190423_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresss',
            name='stu',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
    ]
