# Generated by Django 2.1.7 on 2019-04-23 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_auto_20190423_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresss',
            name='stu',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
    ]
